name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up C++ compiler
      uses: actions/setup-cpp@v2

    - name: Build project
      run: g++ -o myapp main.cpp

    - name: Run tests
      run: ./myapp
